### ISSUE TITLE
Design of update action in users page

### ISSUE THREAD

**Issue by robinpasalosdos** [robinpasalosdos/pupclinic#11]
![image](https://github.com/robinpasalosdos/pupclinic/assets/55908416/2cd03e17-3a9d-47c7-8ef0-ad1212c5dd72)

**Comment by Equirizon** [comment]
👌

**Comment by Equirizon** [comment]
![image](https://github.com/robinpasalosdos/pupclinic/assets/70065461/dbf8ccb6-b76c-4a69-9f02-0c6cadbeac78)
done!
